<?php

namespace Acme\SubscribeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends EntityRepository
{
    public function getLimit($template, $limit = false)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('s')
            ->from('AcmeSubscribeBundle:Subscriber', 's')
            ->leftJoin("s.letters", "l")
            ->where('l = :letter')
            ->setParameter('letter', $template)

            ->orderBy('s.email', 'DESC')
        ;
        if ($limit) {
            $query->setMaxResults($limit);
        }

        return $query->getQuery()->getResult();
    }
}
