<?php

namespace Acme\SubscribeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateLetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateLetterRepository extends EntityRepository
{

}
