<?php

namespace Ads\OfferBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfferTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferTextRepository extends EntityRepository
{
    /**
     * @param array $tagsId
     * @return array
     */
    public function findByTagsId(array $tagsId)
    {
        if (empty($tagsId))
            return array();

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('f')
            ->from('AdsOfferBundle:OfferText', 'f')
            ->join('f.tags', 't')
            ->where('t.id IN ('.join(',', $tagsId).')')
            ->andWhere('f.status = :status')
            ->setParameter('status', 1)
        ;

        $result = $query->getQuery()->getResult();

        return $result;
    }
}
