services:
    ads_offer.admin.offer_text:
        class: Ads\OfferBundle\Admin\OfferTextAdmin
        arguments: [~, Ads\OfferBundle\Entity\OfferText, AdsOfferBundle:OfferTextAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: OfferText}
